### PR TITLE
Corrected ISO code for Great Britain from UK to GB.

### PR DESCRIPTION
**Pull request by pheest**

### CODE REVIEW

**Comment by Neyri** [comment]
Hi, thank you for your contribution. 
If I got the ISO norm right (see link provided https://en.wikipedia.org/wiki/ISO_3166-2:GB), the ISO code *GB* is linked to United-Kingdom and not only Great-Britain. 
Data should then be `Royaume-Uni,0.457,GB`.

**Comment by pheest** [comment]
GB is the ISO code for the "United Kingdom of Great Britain and **Northern Ireland**".
See https://www.britannica.com/story/whats-the-difference-between-great-britain-and-the-united-kingdom

But see also https://help.avalara.com/Frequently_Asked_Questions/AvaTax_FAQ/ACTION_NEEDED%3A__Northern_Ireland_ISO_code_update_for_businesses_selling_into_Northern_Ireland

This is an intensively political point.
I'm not able to test the issue in Northern Ireland, as I don't live there.

**Comment by Neyri** [comment]
Ok, still we must cover Northern Ireland. Based on the provided links, we should add a specific line for Northern Ireland. The energy mix could be either 0.458 (Ireland) or 0.457 (Great Britain) or 0.4575 (average of both).

**Comment by pheest** [comment]
I've been researching and reflecting on this.
I'm _fairly_ sure that the GB code remains applicable for computers in Northern Ireland.
I believe the new XI code is only used for customs and tax purposes, see https://taxation-customs.ec.europa.eu/system/files/2020-11/use_of_gb_and_xi_codes_guidance.pdf

I propose to put 'Grande-Bretagne et Irlande du Nord'.
As a string, this is rather long, but I don't think that matters?

'Royaume-Uni' is confusing in this context, and led to the incorrect UK code being used.
'Grande-Bretagne' alone is inaccurate, and could upset people in Northern Ireland.

Would you agree?

**Comment by Neyri** [comment]
Sounds good to me ! Thank you for the dive in regulations 😉

**Pull request merged**
